// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2w0EdHX8iu7uyOr5iK6rjXMYno26JMv8',
    appId: '1:1048912271648:web:593fa71c1f4d5f03b2df45',
    messagingSenderId: '1048912271648',
    projectId: 'vocemaissegura-4b45a',
    authDomain: 'vocemaissegura-4b45a.firebaseapp.com',
    storageBucket: 'vocemaissegura-4b45a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlUae30FRG1DqilvPfTHwxYpHNmoq3zmo',
    appId: '1:1048912271648:android:51e2ce64d91ffccfb2df45',
    messagingSenderId: '1048912271648',
    projectId: 'vocemaissegura-4b45a',
    storageBucket: 'vocemaissegura-4b45a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDW9SWJeFK8llzUYpVvqsiEIsev1YiZYhc',
    appId: '1:1048912271648:ios:611b6aebbed7df38b2df45',
    messagingSenderId: '1048912271648',
    projectId: 'vocemaissegura-4b45a',
    storageBucket: 'vocemaissegura-4b45a.appspot.com',
    iosBundleId: 'com.example.voceMaisSegura',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDW9SWJeFK8llzUYpVvqsiEIsev1YiZYhc',
    appId: '1:1048912271648:ios:611b6aebbed7df38b2df45',
    messagingSenderId: '1048912271648',
    projectId: 'vocemaissegura-4b45a',
    storageBucket: 'vocemaissegura-4b45a.appspot.com',
    iosBundleId: 'com.example.voceMaisSegura',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2w0EdHX8iu7uyOr5iK6rjXMYno26JMv8',
    appId: '1:1048912271648:web:fffb0204ddb52484b2df45',
    messagingSenderId: '1048912271648',
    projectId: 'vocemaissegura-4b45a',
    authDomain: 'vocemaissegura-4b45a.firebaseapp.com',
    storageBucket: 'vocemaissegura-4b45a.appspot.com',
  );
}
